defaults: &defaults
  docker:
    - image: circleci/node:14.16.0-browsers
  resource_class: small

orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  run_test:
    jobs:
      - test
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - test
      - publish:
          name: Npm publish
          filters:
            branches:
              only: master
          requires:
            - hold

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
          name: Run lint
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Run build
  publish:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/project/.npmrc
      - run:
          name: Publish
          command: npm publish --access=public
